### ISSUE TITLE
Future Development Question(s)

### ISSUE THREAD

**Issue by timatooth** [Raphfrk/ServerPort#25]
Hi Raphfrk,

I was just wondering if you aim to complete the 'Server-Port Suite' (or continue working on ServerPort) with Spoutcraft being the 'client patcher'? Will there be significant technical issues that will result when 1.8 releases ie. Chunks or stream protocol change.

Cheers
Tim

P.S Where is the 'Issues' section for SpoutDev/\* ?

**Comment by Raphfrk** [comment]
It should already work with Spout as the client patcher.  

Nobody knows what 1.8 will bring.  The main thing that might cause issues would be if Notch increased the map height.  However, it isn't likely to happen.

Normally the protocol changes every revision.  However, it normally represents small changes.  Craft Proxy can be reasonably easily upgraded to handle new packets.

I am not really planning on doing much more on the Suite.  It does work as a framework for inter server teleporting.

There is only 1 issues section for Spout, it is all in the Spout repository, rather than spreading issues between all the various sub-projects.

**Comment by timatooth** [comment]
Thanks for clearing that up!  I am really excited about what the SpoutDev team has developed already and in the future too. I will definitely be trying Spoutcraft w/ ServerPort tomorrow.
